ACS_WFC:
  search_pattern:
    - ./../crrejtab/ACS/mastDownload/HST/*/*flt.fits
  hdf5_files:
    - ./../data/ACS/acs_cr_affected_pixels.hdf5
    - ./../data/ACS/acs_shapes.hdf5
    - ./../data/ACS/acs_sizes.hdf5
    - ./../data/ACS/acs_cr_rate.hdf5
  astroquery:
    - '2002-03-01'
WFC3_UVIS:
  search_pattern:
    - ./../crrejtab/WFC3/mastDownload/HST/*/*flt.fits
  hdf5_files:
    - ./../data/WFC3/wfc3_cr_affected_pixels.hdf5
    - ./../data/WFC3/wfc3_shapes.hdf5
    - ./../data/WFC3/wfc3_sizes.hdf5
    - ./../data/WFC3/wfc3_cr_rate.hdf5
  astroquery:
    - '2009-05-01'
STIS_CCD:
  search_pattern:
    - ./../crrejtab/STIS/mastDownload/HST/*/*flt.fits
  hdf5_files:
    - ./../data/STIS/stis_cr_affected_pixels.hdf5
    - ./../data/STIS/stis_shapes.hdf5
    - ./../data/STIS/stis_sizes.hdf5
    - ./../data/STIS/stis_cr_rate.hdf5
  astroquery:
  - '1997-02-01'
subgrp_names:
  - cr_affected_pixels
  - shapes
  - sizes
  - incident_cr_rate
